modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"

[[mods]]
modId="mineria"
version="1.3.0"
displayName="Mineria"
#updateJSONURL="http://myurl.me/"
displayURL="https://mineria-update.fr/"
logoFile="logo.png"
credits="Coded by LGatodu47"
authors="Mathys_craft, Mr-lulu-51, LGatodu47"
description='''
The main mod of Mineria, a Modded PVP-Faction server."
'''

[[dependencies.mineria]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mineria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"